# Generated by Django 4.2.16 on 2025-07-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_pdf_app', '0002_customuser_uploadedpdf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
